danliris/com-danliris-service-purchasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/Expedition/PurchasingDocumentExpeditionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/Expedition/PurchasingDocumentExpedition.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/Expedition/UnitPaymentOrderVerificationViewModel.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/Expedition/PurchasingDocumentExpeditionController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/Expedition/UnitPaymentOrderVerificationController.cs
> add verification ui

- Com.DanLiris.Service.Purchasing.Lib/Facades/Expedition/PurchasingDocumentExpeditionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/Expedition/UnitPaymentOrderVerificationViewModel.cs
update verifcation facade and controller
> update verifcation facade and controller

- Com.DanLiris.Service.Purchasing.Lib/ViewModels/Expedition/UnitPaymentOrderVerificationViewModel.cs
update view model verification
> update view model verification

- Com.DanLiris.Service.Purchasing.Lib/AutoMapperProfiles/GarmentInternalPurchaseOrderProfile.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternalPurchaseOrderFacades/GarmentInternalPurchaseOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentInternalPurchaseOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20181004041043_Add_GarmentInternalPurhaseOrder.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20181004041043_Add_GarmentInternalPurhaseOrder.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentInternalPurchaseOrderModel/GarmentInternalPurchaseOrder.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentInternalPurchaseOrderModel/GarmentInternalPurchaseOrderItem.cs
- Com.DanLiris.Service.Purchasing.Lib/PurchasingDbContext.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternalPurchaseOrderViewModel/GarmentInternalPurchaseOrderItemViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternalPurchaseOrderViewModel/GarmentInternalPurchaseOrderViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentInternalPurchaseOrderControllerTests/GarmentInternalPurchaseOrderControllertest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentPurchaseRequestControllerTests/GarmentPurchaseRequestControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentInternalPurchaseOrderDataUtils/GarmentInternalPurchaseOrderDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentInternalPurchaseOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentPurchaseRequestTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInternalPurchaseOrderControllers/GarmentInternalPurchaseOrderController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
> GarmentInternalPurchaseOrder

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
Search Attributes and Item Status
> Fix GarmentPurchaseRequest

- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/PurchasingDispositionControllers/PurchasingDispositionController.cs
…ngDispositionControllers/PurchasingDispositionController.cs
> Update controller on disposition

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentDeliveryOrderControllerTests/GarmentDeliveryOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
Membuat Service untuk Report dan Export Excel
> Monitoring Delivery Order

- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitReceiptNoteFacade/UnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitReceiptNoteTests/BasicTest.cs
Dengan flow normal harusnya IncomeTaxId by default null. Tapi ternyata isinya "0"
> IncomeTaxId Filter

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Update filter Garment Purchase Monitoring Ketepatan Kedatangan Barang sesuai kategori
> GpurchaseMonitoringKetepatanKedatangan

- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IUnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentOrderViewModel/UnitPaymentOrderReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentDeliveryOrderControllerTests/GarmentDeliveryOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentOrderControllerTests/UnitPaymentOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitPaymentOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitPaymentOrderControllers/UnitPaymentOrderController.cs
Membuat API untuk menu monitoring Surat Perintah Bayar
> Monitoring Surat Perintah Bayar API

- Com.DanLiris.Service.Purchasing.Lib/Facades/ExternalPurchaseOrderFacade/ExternalPurchaseOrderGenerateDataFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/PurchaseRequestFacades/PurchaseRequestGenerateDataFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentCorrectionNoteFacade/UnitPaymentPriceCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitReceiptNoteFacade/UnitReceiptNoteGenerateDataFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IUnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IUnitPaymentPriceCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/ExternalPurchaseOrderViewModel/ExternalPurchaseOrderGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/PurchaseRequestViewModel/PurchaseRequestGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentCorrectionNoteViewModel/UnitPaymentCorrectionNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentOrderViewModel/UnitPaymentOrderGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitReceiptNoteViewModel/UnitReceiptNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/ExternalPurchaseOrderTests/ExternalPurchaseOrderGenerateDataControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/PurchaseRequestControllerTests/PurchaseRequestGenerateDataControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentCorrectionNoteControllerTests/UnitPaymentCorrectionGenerateDataControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentOrderControllerTests/UnitPaymentOrderGenerateDataControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitReceiptNoteTests/UnitReceiptNoteGenerateDataControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/ExternalPurchaseOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/PurchaseRequestTests/MonitoringTests.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitPaymentOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitPaymentPriceCorrectionNoteTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitReceiptNoteTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/ServiceProviderFixture.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/ExternalPurchaseOrderControllers/ExternalPurchaseOrderGenerateDataController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/PurchaseRequestControllers/PurchaseRequestGenerateDataController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitPaymentCorrectionNoteController/UnitPaymentCorrectionNoteGenerateDataController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitPaymentOrderControllers/UnitPaymentOrderGenerateDataController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitReceiptNoteControllers/UnitReceiptNoteGenerateDataController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Facades - Generate Data Textile Purchasing  
Add ViewModels - Generate Data Textile Purchasing  
Add Unit Test - Generate Data Textie Purchasing  
Add Controllers - Generate Data Textile Purchasing
> Add Service - Generate Data Textile Purchasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentCorrectionNoteFacade/UnitPaymentQuantityCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IUnitPaymentQuantityCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentCorrectionNoteViewModel/UnitPaymentQuantityCorrectionNoteReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentCorrectionNoteControllerTests/QuantityCerrectionReportTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitPaymentQuantityCorrectionNoteTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitPaymentCorrectionNoteController/UnitPaymentQuantityCorrectionNoteReportController.cs
Menambahkan menu Monitoring Koreksi Jumlah di menu Purcahase
> Monitoring Koreksi Jumlah ( Purchase )

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/BasicTest.cs
Menambahkan filter Embroidery dan Process
> Garment Monitoring Kedangan Barang

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
Add Field ViewModels Garment Delivery Order
Update Facades Garment Delivery Order
> Update Service : Monitoring Surat Jalan Garment

- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseOrderMonitoringAllFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/InternalPurchaseOrderViewModel/PurchaseOrderMonitoringAllViewModel.cs
> Update monitoring purchase

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentOrderControllerTests/UnitPaymentOrderControllerTest.cs
Update Unit Test & PDF Templete - Surat Perintah Bayar
> Update Unit Test & PDF Templete - Surat Perintah Bayar

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Ubah souce data untuk staff yang tadinya keliru ambil adm
> Monitoring Ketepatan kedatangan

- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseOrderMonitoringAllFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/InternalPurchaseOrderViewModel/PurchaseOrderStaffReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/InternalPurchaseOrderTests/POMonitoringAllControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/InternalPurchaseOrderTests/POMonitoringAllTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/InternalPurchaseOrderControllers/PurchaseOrderMonitoringAllController.cs
menambah menu monitoring kedatangan per staff di purchasing
> Monitoring Kedatangan per Staff

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentExternalPurchaseOrderFacades/Reports/TotalGarmentPurchaseFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/InternalPurchaseOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/InternalPurchaseOrderViewModel/InternalPurchaseOrderUnProcessedReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/InternalPurchaseOrderTests/InternalPurchaseOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/InternalPurchaseOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/InternalPurchaseOrderControllers/InternalPurchaseOrderController.cs
Service PO Internal Belum Dibuat PO External
- Add ViewModels
- Update Facades
- Add Unit Tests
- Add Controllers
> Add Service | PO Internal Belum Dibuat PO External

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IMonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCentralBillReceptionViewModel/MonitoringCentralBillReceptionViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/MonitoringCentralBillReceptionControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.Test/ServiceProviderFixture.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/MonitoringCentralBillReceptionController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Service - Penerimaan Bon Pusat
- ViewModels
- Facades
- Itnerfaces
- Controllers
- StartUp
Add Unit Test - Penerimaan Bon Pusat 
- Facades
- Controllers
> Add Service - Penerimaan Bon Pusat

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillExpenditureFacades/MonitoringCentralBillExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IMonitoringCentralBillExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCentralBillExpenditureViewModel/MonitoringCentralBillExpenditureViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/MonitoringCentralBillExpenditureControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentBeacukaiDataUtils/GarmentBeacukaiDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentUnitReceiptNoteDataUtils/GarmentUnitReceiptNoteDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.Test/ServiceProviderFixture.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/MonitoringCentralBillExpenditureController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Service | Monitoring Pengeuaran Bon Pusat
> Viewmodels, Facades, Interfaces, Controllers, StartUp
Add Unit Test | Monitoring Pengeuaran Bon Pusat
> Controllers, Facades
> Add Service | Monitoring Pengeuaran Bon Pusat

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseOrderMonitoringAllFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentInternNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/InternalPurchaseOrderViewModel/PurchaseOrderMonitoringAllViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentInternNoteTests/GarmentInternNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentInternNoteTests/BasicTests.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/InternalPurchaseOrderTests/POMonitoringAllTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInternNoteControllers/GarmentInternNoteController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/InternalPurchaseOrderControllers/PurchaseOrderMonitoringAllController.cs
> Add Division Filter

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteReceptionFacades/MonitoringCorrectionNoteReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IMonitoringCorrectionNoteReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCorrectionNoteReceptionViewModel/MonitoringCorrectionNoteReceptionViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/MonitoringCorrectionNoteReceptionControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentBeacukaiDataUtils/GarmentBeacukaiDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentCorrectionNoteDataUtils/GarmentCorrectionNoteDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.Test/ServiceProviderFixture.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/MonitoringCorrectioNoteReceptionController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Service | Monitoring Penerimaan Nota Koreksi  
- ViewModels, Facades, Interfaces, Controllers
- StartUp
Add Unit Test | Monitoring Penerimaan Nota Koreksi 
- Controllers Test
- Facades Test
- Update Data Util Garment Bea Cukai & Garment Correction Note
> Add Service | Monitoring Penerimaan Nota Koreksi

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentUnitReceiptNoteViewModels/FlowDetailPenerimaanViewModels.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentUnitReceiptNoteControllerTests/GarmentUnitReceiptNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentUnitReceiptNoteControllers/GarmentUnitReceiptNoteController.cs
menambahkan service laporan  flow detail penerimaan
> Laporan Flow Penerimaan

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillExpenditureFacades/MonitoringCentralBillExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteReceptionFacades/MonitoringCorrectionNoteReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCentralBillExpenditureViewModel/MonitoringCentralBillExpenditureViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCentralBillReceptionViewModel/MonitoringCentralBillReceptionViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCorrectionNoteReceptionViewModel/MonitoringCorrectionNoteReceptionViewModel.cs
Update ViewModels & Facades
- Penerimaan Bon Pusat
- Pengeluaran Bon Pusat
- Peneriman Nota Koreksi
> Update ViewModels & Facades

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteExpenditureFacades/MonitoringCorrectionNoteExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IMonitoringCorrectionNoteExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringCorrectionNoteExpenditureViewModel/MonitoringCorrectionNoteExpenditureViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/MonitoringCorrectionNoteExpenditureControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.Test/ServiceProviderFixture.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/MonitoringCorrectioNoteExpenditureController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Service | Laporan Pengeluaran Nota Koreksi
- ViewModels, Facades, Interfaces, Controllers, StartUp
Add Unit Test } Laporan Pengeluaran Nota Koreksi
- Controllers, Facades
> Add Service & Unit Test | Laporan Pengeluaran Nota Koreksi

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillExpenditureFacades/MonitoringCentralBillExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteExpenditureFacades/MonitoringCorrectionNoteExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteReceptionFacades/MonitoringCorrectionNoteReceptionFacade.cs
Update Facade  | Monitoring Untuk Accounting
- Penerimaan Bon Pusat
- Pengeluaran Bon Pusat
- Peneriman Nota Koreksi
- Pengeluaran Nota Koreksi
> Update Facade | Monitoring Untuk Accounting

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillExpenditureFacades/MonitoringCentralBillExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteExpenditureFacades/MonitoringCorrectionNoteExpenditureFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCorrectionNoteReceptionFacades/MonitoringCorrectionNoteReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingTempViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/GarmentDailyPurchasingReportControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentInvoiceTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentDailyPurchasingReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Service - Garment Daily Purchase Order Report
>> VModel, Facede, Unterfaces, Controller, Start Up
Create Unit Test - Garment Daily Purchase Order Report
>> Controllers & Facades
>> Update Facade - Report Accounting
> Add Service  - Garment Daily Purcahse Order Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitReceiptNoteFacade/UnitReceiptNoteFacade.cs
> fix order to call another service in unit receipt note facade cud

- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitReceiptNoteFacade/IUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitReceiptNoteFacade/UnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitReceiptNoteViewModel/UnitNoteSpbViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitReceiptNoteTests/UnitNoteSpbControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitReceiptNoteTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitReceiptNoteControllers/UnitNoteSpbController.cs
> MonitoringUnitReceiptNoteSPB

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringUnitReceiptFacades/MonitoringUnitReceiptAllFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/MonitoringUnitReceiptAllViewModel/MonitoringUnitReceiptAll.cs
Add data shipmentType, price, user
> Update Monitoring unit receipt note

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/ExternalPurchaseOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNotePricePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNotePricePphPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNotePricePpnPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNoteQuantityPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNoteQuantityPphPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNoteQuantityPpnPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentReturnCorrectionNote/GarmentReturnCorrectionNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentReturnCorrectionNote/GarmentReturnCorrectionNotePphPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentReturnCorrectionNote/GarmentReturnCorrectionNotePpnPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentExternalPurchaseOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentInternNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentQuantityCorrectionNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/VatPDFTemplate.cs
> Update alamat DL

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/PRMasterValidationReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IPRMasterValidationReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/PRMasterValidationReportViewModel/PRMasterValidationReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/PRMasterValidationReportrControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentPurchaseRequestTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/PRMasterValidationReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Unit Test | Garment PR Master Validation Report
Facades, Controller, Dat Units
Add Service | Garment PR Master Validation Report
- Facade, Interface, ViewModels, Controller, StartUp
> Add Service | Garment PR Master Validation Report 

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/PRMasterValidationReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentPurchaseRequestPDFTemplates/GarmentPurchaseRequestPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/PRMasterValidationReportViewModel/PRMasterValidationReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
Update Service | PR Master Validation : ViewModel & Facade
Update PDF Templete | PDF PR Master Garment
> Update Service | PR Master Validation

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/BudgetMasterSampleDisplayFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/PRMasterValidationReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IPRMasterValidationReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/BudgetMasterSampleDisplayViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/PRMasterValidationReportViewModel/PRMasterValidationReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/BudgetMasterSampleDisplayControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/PRMasterValidationReportrControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentPurchaseRequestTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentReportTests/BudgetMasterSampleDisplayFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/BudgetMasterSampleDisplayController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/PRMasterValidationReportController.cs
Update Facade & Unit Test | Garment Report
> Budget Master / Sample Display
> PR Master Validastion Report
> Update Facade & Unit Test | Garment Report

- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentUnitDeliveryOrderViewModel/GarmentUnitDeliveryOrderViewModel.cs
validasi tanggal system dengan tanggal DO
> Validasi Tanggal DO Retur

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitExpenditureNoteFacade/GarmentUnitExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20200518043452_GarmentUnitExpenditureNote_ItemStatus.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20200518043452_GarmentUnitExpenditureNote_ItemStatus.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentUnitExpenditureNoteModel/GarmentUnitExpenditureNoteItem.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentUnitExpenditureNoteViewModel/GarmentUnitExpenditureNoteItemViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentUnitExpenditureNoteControllerTests/GarmentUnitExpenditureNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/DeliveryOrderTests/BasicTest.cs
[5/9 10:39 AM] Nila Ervina
pas gawe Bon Pengeluaran Unit sg tipe EXTERNAL, kui mbiyen enek update DOQuantity ng tabel PO Eks sg lama
na kui ilangono ya..
soale saiki kn wes nganggo sg PO Eks R1 kui, dadi ra perlu update DOQuantity
> Create Bon Pengeluaran External

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDebtBalanceReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDebtBalanceReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentDebtBalanceReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/GarmentDebtBalanceReportControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentDebtBalanceReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Add Service Garment Debt Balance Report
> Add Service Garment Debt Balance Report

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/IncomeTaxPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/VatPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInvoiceControllers/GarmentInvoiceController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitPaymentOrderControllers/UnitPaymentOrderController.cs
unit-payment-order-controller
unit-payment-order-pdf
garment-invoice-controller
incometax-pdf
vat-pdf
> Update PDF Template SPB(P) & Invoice(G-P)

- Com.DanLiris.Service.Purchasing.Lib/Facades/VBRequestPOExternal/SPBDto.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/VBRequestPOExternal/VBRequestPOExternalService.cs
- SPBDto
- VBRequestPOExternalService
> [UPDATE] Enhance VB Request PO External

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/PurchaseRequestPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/PurchasingDispositionPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitReceiptNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/PurchaseRequestControllerTests/PurchaseRequestByUserControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/PurchasingDispositionControllerTests/PurchasingDispositionControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentOrderControllerTests/UnitPaymentOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitReceiptNoteTests/UnitReceiptNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/PurchaseRequestDataUtils/PurchaseRequestDataUtil.cs
Enhancement Cetak PDF : Purchase Requests, Unit Receipt Note, Unit Payment Order, Disposition Payment
> Enhancement Cetak PDF

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentExternalPurchaseOrderFacades/Reports/TopTenGarmentPurchaseFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentInternNotePaymentStatusFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmenInternNotePaymentStatusFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentExternalPurchaseOrderViewModel/Reports/TopTenGarmenPurchasebySupplierViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/GarmentInternNotePaymentStatusReportControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentExternalPurchaseOrderDataUtils/GarmentExternalPurchaseOrderDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentExternalPurchaseOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentInternNoteTests/BasicTests.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentInternNotePaymentStatusReportController.cs
- Monitoring Delivery Order
- Garment Intern Note Payment Status Report
- Top Ten Supplier Report
> Enhancement - Garment Purchasing Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/BankExpenditureNoteFacades/BankExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Expedition/PPHBankExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Services/APIDefaultResponse.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/IntegrationViewModel/DailyBankTransactionViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/PPHBankExpenditureNoteDataUtil/PPHBankExpenditureNoteDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/PPHBankExpenditureNoteTest/BasicTest.cs
- Fix GarmentCurrency Request
- Add CurrencyRate when Posting
> [UPDATE] Enhance PHH & DPP BankExpenditureNote

- Com.DanLiris.Service.Purchasing.Lib/Facades/BankExpenditureNoteFacades/BankExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Expedition/PPHBankExpenditureNoteFacade.cs
- BankExpenditureNote
- PPHBankExpenditureNote
> [UPDATE] Fix Currency Rate on Create

- Com.DanLiris.Service.Purchasing.Lib/Facades/BankExpenditureNoteFacades/BankExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20201104094720_Add_URNId_URNNo_PurchasingDOcumentExpedition.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20201104094720_Add_URNId_URNNo_PurchasingDOcumentExpedition.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20201104094924_Add_URNId_URNNo_BankExpenditureNote.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20201104094924_Add_URNId_URNNo_BankExpenditureNote.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/BankExpenditureNoteModel/BankExpenditureNoteItemModel.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/Expedition/PurchasingDocumentExpedition.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/BankExpenditureNote/BankExpenditureNoteItemViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/Expedition/PurchasingToVerificationViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/Expedition/UnitPaymentOrderViewModel.cs
- PurchasingDocumentExpedition
- BankExpenditureNote
> [UPDATE] Add URNNo & URNId

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseMonitoringService.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseOrderMonitoringAllFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/LocalPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentPurchaseRequestPDFTemplates/GarmentPurchaseRequestPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingTempViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/InternalPurchaseOrderViewModel/PurchaseOrderMonitoringAllViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/Report/LocalPurchasingBookReportTest.cs
- Daily Purchasing Book Report
- Monitoring Purchase By User & All User
- PDF Garment PR Master
- Garment Delivery Order Report
> Enhancement  - Garment Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/BudgetCashflowService/IBudgetCashflowService.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
> Enhancement - Garment Dailly Purchase Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MonitoringROJobOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/MonitoringROJobOrderViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/CostCalculationGarment/CostCalculationGarment_MaterialViewModel.cs
Enhancement Facade, ViewModels
> Enhancement - Monitoring Budget RO Job Order (Used PR Master)

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentDOItemFacade.cs
> Update GarmentDOItemFacade (loader DOItems/more)

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MonitoringROJobOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentInternNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentInternNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingTempViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/MonitoringROJobOrderViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/CostCalculationGarment/CostCalculationGarment_MaterialViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentInternNoteTests/GarmentInternNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentInternNoteTests/BasicTests.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInternNoteControllers/GarmentInternNoteController.cs
- Daily Garment Purchasing Report
- Monitoring Intern Note
> Enhancement - Garment Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/Expedition/UnitPaymentOrderExpeditionReportService.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/Expedition/UnitPaymentOrderExpeditionReportViewModel.cs
Add Payment Method in Laporan Spb
> Add PaymentMethod in Laporan Spb

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDispositionPaymentReport/GarmentDispositionPaymentReportService.cs
…PurchasingDisposistionExpedition
> fixing filter position and get disposition Quantity in report Garment

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentRealizationCMTReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentRealizationCMTReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IUnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDailyPurchasingReportViewModel/GarmentDailyPurchasingReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentRealizationCMTRepotViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/GarmentExpenditureGood/GarmentExpenditureGoodViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentOrderViewModel/UnitPaymentOrderTaxReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentReport/GarmentRealizationtCMTReportControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitPaymentOrderControllerTests/UnitPaymentOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/NewIntegrationDataUtils/GarmentExpenditureGoodDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/UnitPaymentOrderDataUtils/UnitPaymentOrderDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitExpenditureNoteTests/BasicTests.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitPaymentOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentRealizationCMTReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/UnitPaymentOrderControllers/UnitPaymentOrderController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
- Monitoring Surat Jalan Garment
- Report Realisasi CMT
- Monitoring PPN & PPH Textile
- Buku Harian Pembelian Garment
> Enhancement Garment Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
Update Query Monitoring Garment Delivery Order ( URN Type = PEMBELIAN)
> Enhancement Monitoring Garment Delivery Order

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentRealizationCMTReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Monitoing PPN & PPH (Fixing Formula)
- Detail Omzet Export GArment / Unit (Sorting Data)
> Enhancemet - Facade

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentUnitReceiptNoteFacade.cs
> Update urn when create not update dodetail

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentRealizationCMTReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20210617061016_Add-Coloumn-MDStaff-Garment-Purchase-Request.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20210617061016_Add-Coloumn-MDStaff-Garment-Purchase-Request.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentPurchaseRequestModel/GarmentPurchaseRequest.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/GarmentExpenditureGood/GarmentExpenditureGoodViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
- Garment Delivery Order Monitoring
- Garment Realization CMT Report
> Enhancement - G - Purchasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentExternalPurchaseOrderDataUtils/GarmentExternalPurchaseOrderDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitExpenditureNoteTests/BasicTests.cs
- Report Garment Deivery Order
- Report Realization CMT Garment
> Update Unit Test

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20210715155057_Add-Column-MDStaff-In-Table-Garment-Purchase-Order-07-2021.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20210715155057_Add-Column-MDStaff-In-Table-Garment-Purchase-Order-07-2021.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentPurchaseRequestModel/GarmentPurchaseRequest.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
> Enhancement G - Purhasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentExternalPurchaseOrderFacades/GarmentExternalPurchaseOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentExternalPurchaseOrderTests/BasicTest.cs
Tambah validasi jika po eksternal OB maka harus di approve anggaran dulu baru bisa diinput disposisi pembelian.
> Tambah validasi jika po eksternal OB

- Com.DanLiris.Service.Purchasing.Lib/Facades/ExternalPurchaseOrderFacade/MonitoringPriceFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentExternalPurchaseOrderFacades/Reports/TotalGarmentPurchaseFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseOrderMonitoringAllFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentExternalPurchaseOrderViewModel/Reports/TotalGarmentPurchaseBySupplierViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentOrderViewModel/UnitPaymentOrderReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/ExternalPurchaseOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentExternalPurchaseOrderTests/BasicTest.cs
Monitoring Price, Monitoring Surat Jalan, Monitoring SPB, Laporan Total Pembelian Per Supplier
> Enhance - Purchasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitExpenditureNoteFacade/GarmentUnitExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220309095524_add_UnitDO_OtherDescription.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220309095524_add_UnitDO_OtherDescription.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentUnitDeliveryOrder/GarmentUnitDeliveryOrder.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentUnitDeliveryOrderViewModel/GarmentUnitDeliveryOrderViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitDeliveryOrderTests/BasicTests.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitExpenditureNoteTests/BasicTests.cs
> Enhance sprint6 22 uat

- Com.DanLiris.Service.Purchasing.Lib/AutoMapperProfiles/GarmentDeliveryOrderProfile.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentExternalPurchaseOrderFacades/GarmentExternalPurchaseOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220317061313_add-vat-in-garment-delivery-order.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220317061313_add-vat-in-garment-delivery-order.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentDeliveryOrderModel/GarmentDeliveryOrder.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentExternalPurchaseOrderControllerTests/GarmentExternalPurchaseOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentExternalPurchaseOrderControllers/GarmentExternalPurchaseOrderController.cs
> enhance_vat_garment_delivery_order

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
Fix Excel Garment Delivery Order Monitoring
> Fix Excel Garment Delivery Order Monitoring

- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentCorrectionNoteFacade/UnitPaymentPriceCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentCorrectionNoteViewModel/UnitPaymentCorrectionNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentOrderViewModel/UnitPaymentOrderGenerateDataViewModel.cs
> Enhance Generate Data

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
Add Custom Type | Garment Delivery Order Repot
> Enhance - GDO Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteReportViewModel.cs
Add Correction Note & Amount Correction
> Enhance - Garment Intern Note Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitExpenditureNoteFacade/GarmentUnitExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentExternalPurchaseOrderDataUtils/GarmentExternalPurchaseOrderDataUtil.cs
> enhance-garment-uen

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentStockOpnameFacades/GarmentStockOpnameFacade.cs
-Change dbset from UnitReceiptNote to GarmentUnitReceiptNote
> Update Query GarmentStockOpname

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
Reverts danliris/com-danliris-service-purchasing#2205
> Revert "update pemasukan & pengeluaran Mutation Beacukai"

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
> update Excel Garment Purchase Request Facade

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentUnitReceiptNoteControllerTests/GarmentUnitReceiptNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentUnitReceiptNoteControllers/GarmentUnitReceiptNoteController.cs
Unit Receipt Note Service & Controller For Retur Expenditure Good
> Enhance - Unit Receipt Note Service & Controller

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitExpenditureNoteFacade/GarmentUnitExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentUnitExpenditureNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/GarmentDOUrnViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/GarmentUENViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentDeliveryOrderControllerTests/GarmentDeliveryOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentUnitExpenditureNoteControllerTests/GarmentUnitExpenditureNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentUnitReceiptNoteControllerTests/GarmentUnitReceiptNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentDeliveryOrderDataUtils/GarmentDeliveryOrderDataUtil.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentBeacukaiTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitExpenditureNoteTests/BasicTests.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentUnitExpenditureNoteControllers/GarmentUnitExpenditureNoteController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentUnitReceiptNoteControllers/GarmentUnitReceiptNoteController.cs
Unit Receipt Note Service & Controller For Retur Expenditure Good
> Enhance - Unit Receipt Note Service & Controller - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220801031725_Add-Column-ApprovalPR-Garment-Purchase-Request.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220801031725_Add-Column-ApprovalPR-Garment-Purchase-Request.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentPurchaseRequestModel/GarmentPurchaseRequest.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
Add Approval for Kabag Merchandiser
> Enhance - Garment Purchase Request - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentDeliveryOrderControllerTests/GarmentDeliveryOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
> Enhance - GDO Arrival Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentDeliveryOrderControllerTests/GarmentDeliveryOrderControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentDeliveryOrderTests/MonitoringTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentUnitReceiptNoteFacadeTests/GarmentUnitReceiptNoteFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
Modify Service, Controller & Unit Test
> Enhance - Garment Arrival Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220818043739_Add-Column-Approval-Kadiv-On-Garment-PR.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220818043739_Add-Column-Approval-Kadiv-On-Garment-PR.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentPurchaseRequestModel/GarmentPurchaseRequest.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentPurchaseRequestControllerTests/GarmentPurchaseRequestControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
> Enhance PR Master - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220818043739_Add-Column-Approval-Kadiv-On-Garment-PR.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20220818043739_Add-Column-Approval-Kadiv-On-Garment-PR.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentPurchaseRequestModel/GarmentPurchaseRequest.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentPurchaseRequestControllerTests/GarmentPurchaseRequestControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/DataUtils/GarmentPurchaseRequestDataUtils/GarmentPurchaseRequestDataUtil.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
Add Column Approval Kadiv, Modify Service, Controller & Unit Test
> Fix Garment PR MAster

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentFlowDetailMaterialReportFacade.cs
Update Facade - Garment Flow Detail Material
> Enhance Report - Garment Flow Detail Material Report - dev

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentFlowDetailMaterialReportFacade.cs
Update Facade - Garment Flow Detail Material
> Ehance Report - Garment Flow Detail Material Report

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentPurchaseRequestPDFTemplates/GarmentPurchaseRequestPDFTemplate.cs
> Enhance PDF PR Master - Dev

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentPurchaseRequestPDFTemplates/GarmentPurchaseRequestPDFTemplate.cs
> Enhance PDF PR Master

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/AccountingStockReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentStockReportFacade.cs
> enhance-GarmentStockReport

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitExpenditureNoteFacade/GarmentUnitExpenditureNoteFacade.cs
Created For ExpenditureType SubCon
> Modify Garment Unit Expenditure Note

- Com.DanLiris.Service.Purchasing.Lib/Facades/PurchasingDispositionFacades/PurchasingDispositionFacade.cs
Add Vat Tax for Verification Disposition
> Enhance - Purchasing-Dispositiion

- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseMonitoringService.cs
_dbContext.UnitPaymentOrderDetails from URNItems to UPOItems
> fix PurchaseMonitoring

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
Set value PPN  0 if VatRat Null
> bugfix-MonitoringPemasukanBonPusat

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
> enhance-MutationBBCentral

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MonitoringROJobOrderFacade.cs
> Enhance-RO-Job-Order-Report

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/ExternalPurchaseOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentPriceCorrectionNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentQuantityCorrectionNotePDFTemplate.cs
External PO, UnitPaymentOrder, UnitPaymentPriceCorrection, UnitPaymentQtyCorrection
> Update PdfTemplate Purchasing

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/ExternalPurchaseOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentPriceCorrectionNotePDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentQuantityCorrectionNotePDFTemplate.cs
External PO, UnitPaymentOrder, UnitPaymentPriceCorrection, UnitPaymentQtyCorrection
> Update PDF Template Purchasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/MonitoringCentralBillReceptionFacades/MonitoringCentralBillReceptionFacade.cs
Laporan Monitoring Penerimaan Bon Pusat
> BugFix-SetDateTimeData-To-Date

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchasingExpedition/GarmentPurchasingExpeditionService.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchasingExpedition/IGarmentPurchasingExpeditionService.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentPurchasingExpeditionControllerTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchasingExpeditionController.cs
Make Internal Note can be chosen one time
> Add Filtering in Garment Purchasing to Verification

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Fix Formula Monitoring Ketepaan Kedatangan Barang
> Enhance G-Purchasin-Report

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
Remove Receipt Left Over From Receipt
> enhance-BBCentral

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Update Staff  From EPO Createdby
> Enhance Accuracy Of Arrival Report Detail

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentCorrectionNoteFacades/GarmentCorrectionNotePriceFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/ImportPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/LocalPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentCorrectionNoteFacade/UnitPaymentPriceCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentCorrectionNotePriceFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentInternNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentCorrectionNoteViewModel/GarmentCorrectionNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentCorrectionNoteViewModel/UnitPaymentCorrectionNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitPaymentOrderViewModel/UnitPaymentOrderGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentCorrectionNoteControllers/GarmentCorrectionNoteGenerateDataController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInternNoteControllers/GarmentInternNoteGenerateDataController.cs
Generate Data Garment Intern Note & Garment Correction Note
> Create  Generate Data Garment Purchasing

- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentUnitDeliveryOrderViewModel/GarmentUnitDeliveryOrderViewModel.cs
-Ignore Racking for RETUR,SISA,MARKETING
> bugFix_Validation-Racking-UnitDOType

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReceiptCorrectionFacades/GarmentReceiptCorrectionFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentUnitReceiptNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20230612061851_add-coloumt-DOItemsId-GReceiptCorrection.Designer.cs
- Com.DanLiris.Service.Purchasing.Lib/Migrations/20230612061851_add-coloumt-DOItemsId-GReceiptCorrection.cs
- Com.DanLiris.Service.Purchasing.Lib/Models/GarmentReceiptCorrectionModel/GarmentReceiptCorrectionItem.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReceiptCorrectionViewModels/GarmentReceiptCorrectionItemViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentUnitReceiptNoteViewModels/GarmentUnitReceiptNoteItemViewModel.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentUnitReceiptNoteControllers/GarmentUnitReceiptNoteController.cs
-Change Join DOItem from UrnItemId to DoItemsId
> BugFix-GarmentReceiptCorrectionNote

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentImportPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentLocalPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitReceiptNoteTests/UnitReceiptNoteReportControllerTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentImportPurchasingJournalReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Enhance Puchasing Journal
Add Detail Journal
> Enhance Puchasing Journal DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentImportPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentLocalPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentImportPurchasingJournalReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
Enhance Puchasing Journal
Add Detail Journal
> Enhance Puchasing Journal PRD

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
enhance pdf unit payment order
> enhance pdf unit payment order-dev

- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/UnitPaymentOrderPDFTemplate.cs
enhance pdf unit payment order
> enhance pdf unit payment order-prd

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDailyPurchasingReportFacades/GarmentDailyPurchasingReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/ImportPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/LocalPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/Report/ImportPurchasingBookReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/Report/LocalPurchasingBookReportController.cs
Enhancement dilaporan buku harian pembelian garment - data yang muncul per BB per nominal BB Enhancement dilaporan buku pembelian lokal - data yang muncul per bon terima per nominal bon Enhancement dilaporan buku pembelian lokal valas - data yang muncul per bon terima per nominal bon Enhancement dilaporan buku pembelian import - data yang muncul per bon terima per nominal bon
> Enhancement Report G - Purcahsing & Purchasing

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentStockReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
-Change selected data from CreatedUtc to BonDate
> enhance-GStockReport+MutationBB&BP

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDetailLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentDetailImportPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentDetailLocalPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentImportPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentLocalPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/UnitReceiptNoteTests/UnitReceiptNoteReportControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/UnitReceiptNoteTests/BasicTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentDetailImportPurchasingJournalReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentDetailLocalPurchasingJournalReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentImportPurchasingJournalReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentReports/GarmentLocalPurchasingJournalReportController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Startup.cs
create local and import purchasing journal
> create-purchasing-journal UAT

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentImportPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentLocalPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/MutationBBCentralViewModel.cs
enhance laporan mutasi bahan baku & jurnal pembelian
> enhance laporan mutasi bahan baku & jurnal pembelian

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentFlowDetailMaterialReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentUnitReceiptNoteFacades/GarmentUnitReceiptNoteFacade.cs
-change parameter from createdUTc to BonDate
> enhance-ReceiptFlowReport+ExpenditureFlowReport

- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentBeacukaiViewModel/GarmentBeacukaiViewModel.cs
> BugFix-GarmentBeacukai-FixBC262

- Com.DanLiris.Service.Purchasing.Lib/Com.DanLiris.Service.Purchasing.Lib.csproj
- Com.DanLiris.Service.Purchasing.Test/Com.DanLiris.Service.Purchasing.Test.csproj
- Com.DanLiris.Service.Purchasing.WebApi/Com.DanLiris.Service.Purchasing.WebApi.csproj
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInternalPurchaseOrderControllers/GarmentInternalPurchaseOrderController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
> BugFix-Update-csproj-09/04/23

- Com.DanLiris.Service.Purchasing.Lib/Com.DanLiris.Service.Purchasing.Lib.csproj
- Com.DanLiris.Service.Purchasing.Test/Com.DanLiris.Service.Purchasing.Test.csproj
- Com.DanLiris.Service.Purchasing.WebApi/Com.DanLiris.Service.Purchasing.WebApi.csproj
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentInternalPurchaseOrderControllers/GarmentInternalPurchaseOrderController.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentPurchaseRequestController.cs
<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
> MDP newUAT

- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentPurchaseRequestControllerTests/GarmentMonitoringPurchaseAllControllerTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentPurchaseRequestControllers/GarmentMonitoringPurchaseController.cs
- [bugfix monitoring purchase all](https://github.com/danliris/com-danliris-service-purchasing/commit/0d14a02002df8e4384562db2e5e8236273a71afb)
- [update unit test monitoring purchase all](https://github.com/danliris/com-danliris-service-purchasing/commit/e72655b2d0df10539603673937b54550c60025cb)
> bugfix monitoring purchase all

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentLocalPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentCorrectionNoteFacade/UnitPaymentPriceCorrectionNoteFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentImportPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/GarmentLocalPurchasingJournalReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentReports/MutationBBCentralViewModel.cs
> Enhance purchasing jurnal dev

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/MutationBeacukaiFacade.cs
-min value from beginqty and and last qty
> BugFix-GarmentMutationBB-Remove minus value

- Com.DanLiris.Service.Purchasing.Lib/Facades/UnitPaymentCorrectionNoteFacade/UnitPaymentPriceCorrectionNoteFacade.cs
> Update Generate Data Correction Note

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentStockOpnameFacades/GarmentStockOpnameFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentStockOpnameFacades/IGarmentStockOpnameFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitReceiptNoteViewModel/UnitReceiptNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentStockOpnameControllerTests/GarmentStockOpnameControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentStockOpnameTests/GarmentStockOpnameFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentStockOpnameControllers/GarmentStockOpnameController.cs
Add column DONo & Arrival Date
> enhance-gmt-stock-opname-dev

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentStockOpnameFacades/GarmentStockOpnameFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentStockOpnameFacades/IGarmentStockOpnameFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/UnitReceiptNoteViewModel/UnitReceiptNoteGenerateDataViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentStockOpnameControllerTests/GarmentStockOpnameControllerTest.cs
- Com.DanLiris.Service.Purchasing.Test/Facades/GarmentStockOpnameTests/GarmentStockOpnameFacadeTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentStockOpnameControllers/GarmentStockOpnameController.cs
Add column DONo & Arrival Date
> enhance-gmt-stock-opname-uat

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/GarmentDeliveryOrderReportViewModel.cs
Service DMS Menambahkan fasilitas export excel di menu mon SJ (tambah data code, buyer & article)
> Service DMS Menambahkan fasilitas export excel di menu mon SJ SPRINT 24

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailImportPurchasingJournalReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentDetailLocalPurchasingJournalReportFacade.cs
> Enhance Purchasing Journal - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseMonitoringService.cs
Enhance Query Monitoring Purchase All
> Enhance Monitoring Purchase All - DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseMonitoringService.cs
Enhance Query Monitoring Purchase All
> Enhance Monitoring Purchase All - UAT

- Com.DanLiris.Service.Purchasing.Lib/Facades/InternalPO/PurchaseMonitoringService.cs
Enhance Query Monitoring Purchase All
> Enhance Monitoring Purchase All - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Update Tanggal Datang diambil dari kolom ArrivalDate
> Enhance Repoert Ketepatan KEdatangan Barang-DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Update Tanggal Datang diambil dari kolom ArrivalDate
> Enhance Repoert Ketepatan KEdatangan Barang-UAT

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentBC23ReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/GarmentSupplierViewModel.cs
> Enhance-Report-BC-23 - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentReports/GarmentBC23ReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/NewIntegrationViewModel/GarmentSupplierViewModel.cs
> Enhance-Report-BC-23 - UAT

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNotePricePpnPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNoteQuantityPpnPDFTemplate.cs
> 2024/#16/Enhance-PDF-Gorrection-Note - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNotePricePpnPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNoteQuantityPpnPDFTemplate.cs
fix formula vatrate
update query filter for arrival report
> 2024/#16/Enhance-PDF-Correction-Note - UAT

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNotePricePpnPDFTemplate.cs
- Com.DanLiris.Service.Purchasing.Lib/PDFTemplates/GarmentCorrectionNotePDFTemplates/GarmentCorrectionNoteQuantityPpnPDFTemplate.cs
Fix query filter for arrival report
mofidy PDF Correction Note ( Vat Rate )
> 2024/#16/Enhance PDF Correction-Note - DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/VBRequestPOExternal/UnitCostDto.cs
Bugfix Loader Intern Note for VB Realization
> 2024/#18/Bugfix Loader Intern Note - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/VBRequestPOExternal/UnitCostDto.cs
> 2024/#18/Fix UnitCostFprVBRealization-PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteReportViewModel.cs
> 2024/#19/Enhance-Sarmut-And-Monitoring-NI - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentExternalPurchaseOrderFacades/GarmentExternalPurchaseOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/VBRequestPOExternal/UnitCostDto.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentExternalPurchaseOrderViewModel/GarmentExternalPurchaseOrderOverBudgetMonitoringViewModel.cs
> 2024/#18/Enhance EPO Over Budget - UAT

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteReportViewModel.cs
> 2024/#19/Enhance-Sarmut-And-Monitoring-NI - DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Enhance % OK & Not OK Keterpatan Kedatangan Barang Garment
> 2024/#19/Enahnce-Service-Gmt-Delivery-Order - DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/LocalPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/OverBudgetQtyReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentInternNoteTests/GarmentInternNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
> 2024/#22/Create Report Over Budget Qty - DEV

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/Report/LocalPurchasingBookReportFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Interfaces/IGarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentDeliveryOrderViewModel/OverBudgetQtyReportViewModel.cs
- Com.DanLiris.Service.Purchasing.Test/Controllers/GarmentInternNoteTests/GarmentInternNoteControllerTest.cs
- Com.DanLiris.Service.Purchasing.WebApi/Controllers/v1/GarmentDeliveryOrderControllers/GarmentDeliveryOrderController.cs
Create Module Report Over Budget Quantity
> 2024/#22/Create Report Over Budget QTY - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentInternNoteFacades/GarmentInternNoteFacades.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentPurchaseRequestFacades/GarmentPurchaseRequestFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/ViewModels/GarmentInternNoteViewModel/GarmentInternNoteReportViewModel.cs
Monitoring NI - Add EPO
Monitoring PO - Fix Budget Qty
> 2024/#22/Enhance Monittoring NI And PO All - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDispositionPurchaseFacades/GarmentDispositionPurchaseFacade.cs
Fixing query & format filter tanggal
> 2024/#22/Enhance-Report-OB-Qty-And-Payment-Invoice - PRD

- Com.DanLiris.Service.Purchasing.Lib/Facades/GarmentDeliveryOrderFacades/GarmentDeliveryOrderFacade.cs
Add Indikator Delivery Pengiriman
> 2024/#25/Update Excel Monitoring Delivery Pengiriman - PRD
